use polars::prelude::*;

// #[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[derive(Debug, Clone)]
pub enum Action {
    Tick,
    Render,
    Resize(u16, u16),
    Suspend,
    Resume,
    Quit,
    Refresh,
    Error(String),
    Help,
    ToggleShowHelp,
    ScheduleIncrement,
    ScheduleDecrement,
    Increment(usize),
    Decrement(usize),
    ScrollUp,
    ScrollDown,
    CompleteInput(String),
    EnterNormal,
    EnterInsert,
    EnterProcessing,
    ExitProcessing,
    Update,
    // etop-specific
    IncrementBlock,
    DecrementBlock,
    IncrementWindow,
    DecrementWindow,
    LiveWindow,
    CheckBlockSet,
    PreviousWindow,
    ScheduleIncrementWindow,
    BeginBlockSubscription,
    BlockSeen(u32),
    UpdateData,
    // LoadDataset(String),
    // NewWarehouse(DataWarehouse),
    RequestQuery(etop_core::DatasetQuery),
    ReceiveQuery(etop_core::DatasetQuery, DataFrame),
    ReceiveQueries(Vec<(etop_core::DatasetQuery, DataFrame)>),
    Log(String),
    RerenderTable,
}
